### ISSUE TITLE
shellcheck warnings on check_auditd.sh

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/nagios-checks#2]
I considered the following warnings from shellcheck to be relevant:

```
if [[ ${STATUS[@]:0:1} == 'AUDIT_STATUS:' ]]; then
      ^-- SC2199: Arrays implicitly concatenate in [[ ]]. Use a loop (or explicit * instead of @).
```

Filed koalaman/shellcheck#885 to fix this, as you're correctly slicing to a single element.

```
EX=$(($EX+2))
      ^-- SC2004: $/${} is unnecessary on arithmetic variables.
```

This one's valid enough.

No other warnings, neat!

**Comment by floatingatoll** [comment]
The first one turns out to be buggy, as it can expand to either 0 or 1 elements, which causes [[ syntax errors. Use ${STATUS[0]} instead.

**Comment by koalaman** [comment]
It works in `[[`, but only thanks to the mentioned implicit concatenation. In `[` it would fail for 0 elements.

Since it's arguably better to be explicit about what should happen if there are no elements, you can use `"${STATUS[*]:0:1}"`  (or just `"${STATUS[0]}"`) to explicitly let 0 elements become the empty string.
